spring:
  application:
    name: rdating
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/rdating}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

reddit:
    client:
        id: ${REDDIT_CLIENT_ID}
        secret: ${REDDIT_CLIENT_SECRET}
        user-agent: ${REDDIT_USER_AGENT}
        username: ${REDDIT_USERNAME}
        password: ${REDDIT_PASSWORD}
    subreddit:
        name: ${REDDIT_SUBREDDIT_NAME}
    authUrl: https://www.reddit.com/api/v1/access_token
    apiBaseUrl: https://oauth.reddit.com
    baseUrl: https://www.reddit.com
    redirectUrl: ${REDDIT_REDIRECT_URL}

logging:
  level:
    root: INFO