CREATE TABLE IF NOT EXISTS `post` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id VARCHAR(255) NOT NULL,
    title TEXT NOT NULL,
    permalink TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE `post` ADD CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users(id);

CREATE UNIQUE INDEX idx_user_id ON `post`(user_id);